# 서울에 위치한 식당들의 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수를 조회하는 SQL문
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I, REST_REVIEW R
WHERE 1=1 
  AND I.REST_ID = R.REST_ID
  # AND ADDRESS LIKE '%서울%'
  AND SUBSTR(ADDRESS, 1, 2) = '서울'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;